name: app_fitoterappia
description: "App fitoterapia para cultivo, apllicaciones, precauciones y recursos."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.4
  path_provider: ^2.0.11  # Última versión
  shared_preferences: ^2.0.11
  flutter_dotenv: ^5.0.2
  diacritic: ^0.1.3
  youtube_player_flutter: ^9.1.1
  cached_network_image: ^3.4.1
  word_search_safety: ^0.1.2-nullsafety.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  http:
  flutter_launcher_icons:

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/logos/
    - assets/images/
    - .env
